nvim-lualine/lualine.nvim

lua/lualine/components/branch.lua
lua/lualine/components/filetype.lua

When I installed this plugin without any Webdevicons plugins already installed, I received an error on opening any file due to the WebDevIcons function not existing.
It turns out that the return from checking if the 'WebDevIconsGetFileTypeSymbol'  function exists returns a 0 if it does not exist, so I just updated accordingly.

Quick fix for checking if the function 'WebDevIconsGetFileTypeSymbol' exists

---

lua/lualine/highlight.lua

A solution to #13 
Since I'm setting defaults here, I though we could make element `(x,y,z)` default to `(c,b,a)`. And separate them in internal code . So if a theme author specifies `(x,y,z)` it statusline will be themed acording to that . otherwise left and right side will be symetrical by default .
So I've also added a implementation for   #25

Themes now fallback to normal mode theme

---

lua/lualine/components/mode.lua
lua/lualine/highlight.lua

regarding #35 
I donn't think all the modes make sence .
We could add the nessary modes to the list . And handle the other so they donn't make lualine crash .
This patch makes the modes that aren't defined to use normal mode highlighting.
Also I've switched select mode to use visual mode highlighting.

Handle undefined mode && fallback to normal mode highlighting

---

lua/lualine.lua

Wraping autocmd with augroup so multiple autocommands aren't created due to multiple calls to lualine.status() .

Putting autocomands in a  group

---

lua/lualine/components/signify.lua

fixing #50
[added, modified, removed] = [-1, -1, -1] was a error code that was
being ignored
I think we should use sy#repo#get_stats_decorated()
insted of sy#repo#get_stats()

Fixed signify component apearing on non repo buffer

---

lua/lualine.lua

Insted of having vim.cmd for each vimL line we can wrap the whole thing in vim.api.nvim_exec

run vimscript inside vim.api.nvim_exec

---

THEMES.md
lua/lualine/themes/codedark.lua

Ported from [vim-code-dark](https://github.com/tomasiser/vim-code-dark) using [lightline2lualine_theme_converter.lua](https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9).

Add codedark theme

---

lua/lualine/components/signify.lua

It is not very informative to have indicators in our statusline that tell us that there are 0 deletions or additions etc. This proposed change will only display relevant indicators if they have a count > 0. This leads to a cleaner statusline that is less cluttered and removes the dreaded '+0 -0 ~1' scenarios. Instead, only '~1' would show in that instance 😀

Don't show signify status symbols if the count < 1

---

README.md
doc/lualine.txt
lua/lualine.lua
lua/lualine/components/signify.lua
lua/lualine/highlight.lua
lua/lualine/utils/component.lua
lua/lualine/utils/utils.lua

It's basicaly merge of #55 and #60 + some fixes and improvements.
The #55 couldn't handle special highlighting in #60 there were some conflits too , I've fixed it .
Changes:
- added component separators{left, right}
- added section separators{left, right}
- We were creating too many unnessary highlight groups (for providing defaults) . I've changed that . removed `apply_defaults` function from highlights.lua . Defaults are handled by `format_highlight` function directly
- Added `get_transition_highlight` function that provides highlight groups for section_separator.
- Other miscellanious changes to make everything work
**for review**:
Changes are confined in:
- lua/lualine.lua 
- lua/lualine/highlight.lua
- lua/lualine/utils/component.lua
**Notes:** If custom haghlights are managed by …

Powerline like section seperators v2

---

lua/lualine.lua
lua/lualine/highlight.lua
lua/lualine/utils/utils.lua

- defaults for themes are directly handled
insted of creating highlight groups for
all posibilities
This was part of separator pr you merged today . I held it back in last moment as I couldn;t resolve a bug . No that bug has been resolved
@hoob3rt can you merge this quickly

Enhancement: Stop creating unnececery hl groups

---

CONTRIBUTING.md
lua/lualine/highlight.lua
lua/lualine/themes/16color.lua
lua/lualine/themes/dracula.lua
lua/lualine/themes/forest_night.lua
lua/lualine/themes/gruvbox.lua
lua/lualine/themes/gruvbox_material.lua
lua/lualine/themes/molokai.lua
lua/lualine/themes/nord.lua
lua/lualine/themes/onedark.lua
lua/lualine/themes/onelight.lua
lua/lualine/themes/powerline.lua
lua/lualine/themes/solarized_light.lua
lua/lualine/themes/wombat.lua

Addressing issue #110
- Removed cterm values from themes
- highlight function nolonger accepts cterm colors insted they are always genarated
- removed cterm color related instructions from CONTRIBUTING.md

Refactor: removing cterm colors from themes

---

README.md
doc/lualine.txt
lua/lualine/components/diff.lua

Changes logic to store diffs in `git_diff` because the original has
stored them in a list:
```
{1, 2, 3} => {added = 1, modified = 2, removed = 3}
```

Enable to set symbols for diff component

---

lua/lualine/components/diagnostics.lua
lua/lualine/components/diff.lua
lua/lualine/highlight.lua
lua/lualine/init.lua
lua/lualine/utils/utils.lua

- Previously custom highlights/component highlights had to callexpand_set_theme to make them restored . That's unintuative . Now any highlight created by lualine.highlight.highlight() will be restored :)
- Renamed component -> var_name in special variable component | Proper BugFix

Refactor: Highlight restoring after ColorScheme

---

lua/lualine/components/diagnostics.lua
lua/lualine/highlight.lua
lua/lualine/init.lua
lua/lualine/utils/section.lua
lua/lualine/utils/utils.lua

Changes:
- loaded theme table is nolonger stored in 
configs and thus not passed
to components. Insted it's cached in highlights.lua
- Reintroducing clear_highlights turns out themes can still change if
setup is called more than once
- Now lualine doesn't crash from invalid theme name
These changes are actually better out of #141 luckily cherry-pick went easy on me this time .
There's one more line of highlight change that I would like to bring here but int's too deep . I might look into it later if #141 isn't merged by then :)

Enhance theme

---

lua/lualine/init.lua

This was the original behaviour before 37a3b8c, using the provided `config.options.theme` as a dictionary to build highlight groups unless it's a string.

Fix: Restore support for dictionary-typed theme setup parameter

---

CONTRIBUTING.md
README.md
doc/lualine.txt
doc/tags
lua/lualine/component.lua
lua/lualine/components/special/eval_func_component.lua
lua/lualine/highlight.lua
lua/lualine/init.lua

1. Add condition option
I quite like the idea of conditions from galaxyline . This pr adds condtion option . It works similer to galaxylines condition . It takes a function . And if the function returns true the component is displayed otherwise it isn't .
2. Also I've updated the options section of docs . What I wrote last time was too confusing even for me 😅 . These changes are on separate commits so don't sqash them .
3. color option now can take a highlight group name insted of bg/fg table
4. evil_lualine screenshot
5. mention lightline2lualine_converter in CONTRIBUTING.md
6. load cterm colors only when termguicolors is disabled to reduce startup overhead
7. Now functions are no longer exposed as global variable
8. Cleanup eval_lua component and document it
9. Document theme tweeking …

Miscellaneous changes

---

lua/lualine/components/special/functon_component.lua

When the provided function has an optional argument the previous
implementation caused error.

BugFix: Fix function component not working

---

lua/lualine/components/special/eval_func_component.lua

nil check was unintentionally removed in 77c4c4748254cd6087c6cc1e8be72485d278eb48

BugFix: fix vim functions displaying nil

---

lua/lualine/components/special/eval_func_component.lua

This can differentiate between string 'nil' and value nil.
Plus cleaner IMO

Better fix to nil on vimfunc

---

lua/lualine/utils/section.lua

If a highlight name is passed as color option's value the component separators weren't previously removed

Fix component separator not removed for string color

---

lua/lualine/themes/ayu_dark.lua
lua/lualine/themes/ayu_light.lua
lua/lualine/themes/ayu_mirage.lua
lua/lualine/themes/codedark.lua
lua/lualine/themes/gruvbox_material.lua
lua/lualine/themes/iceberg_dark.lua
lua/lualine/themes/iceberg_light.lua
lua/lualine/themes/jellybeans.lua
lua/lualine/themes/material.lua
lua/lualine/themes/nightfly.lua
lua/lualine/themes/oceanicnext.lua
lua/lualine/themes/palenight.lua
lua/lualine/themes/seoul256.lua

Some themes set the `bold` attribute incorrectly.
This is probably due to an error in [lightline2lualine theme converter](https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9).

Fix themes incorrectly setting the bold attribute

---

lua/lualine/highlight.lua
lua/lualine/init.lua
lua/lualine/utils/section.lua

Changes:
- transitional_highlight isn't created when both retrieval of fg or bg
has failed
- Transitional highlight is not looked for when section separators are
disabled
- empty section no longer returns highlight group as section data
It possibly resolves #193 .

Fix: Transitional highlight not found error

---

lua/lualine/init.lua

Providing a default config is great but that coliding with user config not so much . And having both vim and  lua styled config are a caos this pr fixes that by reseting the config table before applying a new config .

Clear old config before applying a  new one

---

lua/lualine/init.lua

deepcopying default config is not reverted . And user config is always applied on top of default_config. Functionaly it should be same as before f98e8514
closes #208

Revert f08e8514 partially

---

.github/workflows/ci.yml
.github/workflows/lint.yml

I think what we need is this .
I tested at on my fork . https://github.com/shadmansaleh/lualine.nvim/pull/1
Runs tests when pr is opened , when following commits are pushed to the pr and when pr is merged (check mark in the logs is nice :] )
checkout my fork .
Most of the workflows I've checked are directly using on : [push, pull_request] . We can isolate the push event to master branch only . So if another branch is created in main repo pushing to it won't trigger workflow . But if that branch has a pull request it will .

Fix workflows running twice

---

README.md
doc/lualine.txt
lua/lualine/extensions/quickfix.lua
lua/lualine/init.lua

changes statusline behaviour on quickfix list

feat: quickfix extension

---

lua/lualine/components/diff.lua

This makes the diff component present when initialized. Currently, when opening a file on startup, the component only appears once the `BufEnter` autocmd's are executed.

enhancement: show diff when component is loaded

---

CONTRIBUTING.md
lua/lualine/highlight.lua

If theme for x,y,z is unspecified the default to c,b,a respectively
Follow up on #31 
resonable solution to #227
The refractors I did to highlighter made it simple to allow this . So just flipping the switch here :)
@hoob3rt I think we should allow this . This is 100% backword compatable and absolutly optional . But makes asymatric themeing easily possible .

Allow x,y,z section to be themed independenly

---

lua/lualine/extensions/quickfix.lua

Adds a separate label for locations lists than for quickfix lists. The logic is a bit roundabout, but I don't know of any better way to tell the difference between the two list types.

Quickfix extension: label for location list

---

README.md
doc/lualine.txt
lua/lualine/components/diagnostics.lua

I split the hint diagnostics out to be displayed separately. I'm not really sure why they were combined.
The default color and symbol can be changed to whatever folks prefer. I just put in what seemed useable.
It also looks like style warnings and errors were being ignored from ALE, so I added those into the error and warning counts, respectively. Let me know if this is something we don't actually want though.
I haven't had the opportunity to test yet with ALE or coc.nvim, so I'd love help with that. Otherwise I'll try to get to it this weekend if time allows.

feat: add separate hint diagnostic

---

lua/lualine/components/filetype.lua

Enhances icon detection for files without extension e.g. shebang or
modeline by using filetype option before the extension.

enhance(filetype): filetype option as fallback of file extension for icon detection

---

README.md
doc/lualine.txt
lua/lualine/components/buffers/buffer.lua
lua/lualine/components/buffers/init.lua

Hey!
Here's a little feature to the `buffers` component which allows to display buffer index (also known as "number")
It's useful when you have mappings like `4gb` (open buffer 4).
Thanks for the plugin, btw!

feature(buffers): option to show buffer index

---

lua/lualine/highlight.lua

Found this pretty confusing when trying to set up a theme.
I have a custom theme something like below in which I wanted to customise the `y` section on for `inactive`. This unfortunately didn't work and left me scratching my head for some time.
I think this PR addresses the bug and has fixed the problem for me.
```lua
local nord_theme = {
normal = {
a = {bg = colors.nord8_gui, fg = colors.nord0_gui},
b = {bg = colors.nord1_gui, fg = colors.nord4_gui},
c = {bg = colors.nord3_gui, fg = colors.nord4_gui}
},
insert = {
a = {bg = colors.nord4_gui, fg = colors.nord0_gui},
b = {bg = colors.nord1_gui, fg = colors.nord4_gui},
c = {bg = colors.nord3_gui, fg = colors.nord4_gui}
},
visual = {
a = {bg = colors.nord7_gui, fg = colors.nord0_gui},
b = {bg = colors.nord1_gui, fg = colors.nord4_gui},
c = …
```

Fix: Right highlight groups require explicit normal mode set

---

lua/lualine.lua

According to nvim document,
```txt
Note: The ":autocmd" command can only be followed by another command when the
'|' appears where the pattern is expected.  This works:
:augroup mine | au! BufRead | augroup END
But this sees "augroup" as part of the defined command:
:augroup mine | au! BufRead * | augroup END
:augroup mine | au BufRead * set tw=70 | augroup END
Instead you can put the group name into the command:
:au! mine BufRead *
:au mine BufRead * set tw=70
Or use `:execute`:
:augroup mine | exe "au! BufRead *" | augroup END
:augroup mine | exe "au BufRead * set tw=70" | augroup END
```
After call ```vim.cmd [[augroup lualine | autocmd! | augroup END]]```, we select ```lualine``` group, but don't go back to default group.
More detail, see: …

Fix: remove commands in default group when reset lualine

---

README.md
doc/lualine.txt
lua/lualine/components/filename.lua

This makes the `[No Name]` text, which is shown when a buffer is unnamed, customizable.

feat(filename): add unnamed option

---

lua/lualine/components/filename.lua

Currently if you're editing a readonly file and made any changes, only the modified symbol is shown. With this PR it will show both.

fix: don't hide readonly symbol when modified

---

README.md

This MR fixes a few typos I encountered while reading through lualine's documentation. 
I've also tried to reformat ~~parts~~ most of the documentation to keep the same style across the whole thing.

docs: keep the same style across documentation & fix some typos

---

README.md

Happy new year, fellow lualine devs, contributors and users :partying_face: I've made an effort to (hopefully) improve the readability of lualine's documentation. Please note that the examples I have provided mostly ignore proper casing rules, which is a big deal. This MR does not make that mistake.
- Try (in most cases) to pad the inside of curly braces with a space, e.g.:
```lua
-- Previously:
sections = {lualine_c = {"os.date('%a')", 'data', "require'lsp-status'.status()"}}
-- Now:
sections = { lualine_c = { "os.date('%a')", 'data', "require'lsp-status'.status()" } }
-- Cases when not to:
sections = { lualine_a = {'FugitiveHead'} }
--                       ^^^^^^^^^^^^^^^^
```
- Always begin a line with "Note:" when going into detail for a specific option, where the details aren't …

Enhanced readability for lualine's documentation

---

lua/lualine.lua

The tabline isn't drawn until scrolling the window or opening another file. Opening multiple files at once (e.g. nvim a.txt b.txt) will only show the first.
By performing a deferred redraw of the tabline this fixes this startup behaviour problem.

Schedule a redraw of tabline when setting tabline

---

lua/lualine/utils/notices.lua
lua/lualine/utils/utils.lua

Fixes an issue where an exception that is caused by `win_getid` can sometimes get triggered. Using the direct API call seems to fix that.

fix: use nvim-api to avoid win_getid exceptions

---

lua/lualine/components/branch/git_branch.lua
lua/lualine/components/branch/init.lua
lua/lualine/components/buffers/buffer.lua
lua/lualine/components/buffers/init.lua
lua/lualine/components/diagnostics/init.lua
lua/lualine/components/diagnostics/sources.lua
lua/lualine/components/diff/git_diff.lua
lua/lualine/components/diff/init.lua
lua/lualine/components/tabs/tab.lua

Remove some overhead by using `vim.api` directly

refactor: use nvim api directly for bufnr

---

lua/lualine.lua

Stumbled across minor typo in code comment doc.

fix: code doc typo in lualine.lua

---

THEMES.md
lua/lualine/themes/onedark.lua
lua/lualine/themes/onelight.lua

Good day @shadmansaleh. In my opinion, we use wrong One Color Theme versions, especially for light one: the level of saturation is lower and colors don't match. This MR intends to use [rakr/vim-one](https://github.com/rakr/vim-one) colors range as a baseline for better user experience.
After the changes, schema will look like:
Which matches both: light and dark variant.
Where:
* gray1 is mono_2
* gray2 is syntax_cursor
* gray3 is visual_grey

fix: use one theme colors from rakr/vim-one

---

lua/lualine.lua
lua/lualine/utils/utils.lua

If keyboard interrupt occurs while lualine is evaluating statusline
lualine crashes completely. Since keyboard interrupt isn't something
we can handle try to mitigate the issue by retrying to evaluate the
statusline on error.After this lualine will retry 3 times before giving
up on an runtime error.
closes #531

fix: lualine crashing because of keyboard interrupt.

---

lua/lualine/themes/onedark.lua
lua/lualine/themes/onelight.lua

Since no command mode color was specified for onedark / onelight, I set the unused yellow.

feat: add onedark/onelight command mode color

---

Makefile
README.md
doc/lualine.txt
examples/evil_lualine.lua
lua/lualine.lua
lua/lualine/component.lua
lua/lualine/components/buffers/buffer.lua
lua/lualine/components/buffers/init.lua
lua/lualine/components/diagnostics/init.lua
lua/lualine/components/diff/init.lua
lua/lualine/components/filetype.lua
lua/lualine/components/tabs/init.lua
lua/lualine/components/tabs/tab.lua
lua/lualine/highlight.lua
lua/lualine/utils/loader.lua
lua/lualine/utils/section.lua
lua/lualine/utils/utils.lua
lua/tests/helpers.lua
lua/tests/spec/component_spec.lua
lua/tests/spec/utils_spec.lua

Now you can use function that return the color definitions in any kind of color options (And yes in themes too)
For example here's how mode component is defined in `examples/evilline.lua` now
```lua
{  function() return '' end,
color = function()
-- auto change color according to neovims mode
local mode_color = {
n = colors.red,
i = colors.green,
v = colors.blue,
[''] = colors.blue,
V = colors.blue,
c = colors.magenta,
no = colors.red,
s = colors.orange,
S = colors.orange,
[''] = colors.orange,
ic = colors.yellow,
R = colors.violet,
Rv = colors.violet,
cv = colors.red,
ce = colors.red,
r = colors.cyan,
rm = colors.cyan,
['r?'] = colors.cyan,
['!'] = colors.red,
t = colors.red,
}
return { fg = mode_color[vim.fn.mode()] }
end,
}
```

feat: dynamic color

---

lua/lualine/components/diagnostics/init.lua
lua/tests/spec/lualine_spec.lua
lua/tests/statusline.lua

When each "sub-section" of the diagnostic components have a different background the rendering is off when
multiple more than one of them is shown.
Before:
After:
I didn't want to add any new configuration so I decided to with detecting different background colors since it's this change of color which requires the extra padding.

feat(diagnostics): add padding when using different background colors

---

lua/lualine/components/filename.lua

After https://github.com/nvim-lualine/lualine.nvim/pull/613 , I think shortening target calculation should be based on `columns` option if using `globalstatus`, otherwise, `filename` shortening occurs when we open a new split
> Enabling global statusline, shortening based on window width
---
> Global statusline, shortening based on `columns` option

fix(filename): use columns for shortening if using global statusline

---

README.md
lua/lualine/components/buffers/buffer.lua
lua/lualine/components/buffers/init.lua

Add an option `hide_filename_extension` to `buffers` components.
The file kind icon already indicates filetype. Hidng extensions can save more spaces.

feat: hide filename extension for buffers component

---

README.md
doc/lualine.txt
lua/lualine/components/buffers/buffer.lua
lua/lualine/components/buffers/init.lua

**Features:**
Neovim's bufnr sometimes may very strange when it's number not as same as the order of buffers component. So I add buffer index, which index is as same as buffers component.
In this picture, you can see the number of buffer component are different from bufnr.
I wont delete code about bufnr, I just add buffer index.

feat: show index in buffers component instead of bufnr

---

lua/lualine/components/filesize.lua

Hi! I changed the filesize component a bit so the filesize is always up-to-date by using vim.fn.wordcount().bytes. I removed the decimal for the bytes, since I don't think you can have half a byte, and I fixed a typo. Let me know what you think!
See preview:
[![asciicast](https://asciinema.org/a/qyrJ9MVTdf7hPVh7qpFEcVo1S.svg)](https://asciinema.org/a/qyrJ9MVTdf7hPVh7qpFEcVo1S)

feat: live filesize

---

README.md
lua/lualine/component.lua
lua/lualine/components/filetype.lua
tests/spec/component_spec.lua

I was about to open an issue for this but figured it seemed easy enough.
Here is the issue template I was going to provide.
Set: `icon_right = true`
Allow component icons to be displayed on both the left and right side.
Seems fairly simple and I like the look.

feat: add option to invert component icon alignment

---

README.md
lua/lualine/extensions/man.lua

This will be used with Neovim's built-in `:Man` command and `man` filetype.

feat: Add an extension for man pages

---

README.md
lua/lualine.lua
lua/lualine/config.lua
lua/lualine/utils/loader.lua
lua/lualine/utils/nvim_opts.lua
lua/lualine/utils/utils.lua
tests/spec/config_spec.lua
tests/spec/lualine_spec.lua

Try testing this branch and if you find any issue let me know in comment
With this lualine will control it's own refresh instead of relying on nvim.
If we refresh this way we should be able to change out the statusline, winbar, tabline options and still be running . We should be able to address https://github.com/nvim-lualine/lualine.nvim/pull/689#issuecomment-1157194479 & #395 with this style of update.
-  lualine now refresh based on timer + some auto-commands.
- added `require('lualine').refresh` function to force refresh lualine . It can refresh all statusline, tabline, winbars or can granularly refresh specific statusline/tabline/winbar of specific windows see the code docs for more info.
-  winbar support. (originally form #689 by @diegodox)
- winbar support in extensions.
-  newly …

feat: refresh lualine based on timer + winbar support. (experimental)

---

lua/lualine.lua

Lualine updates in normal mode already (CursorMoved), the same behavior
is useful in insert mode.

enhance: refresh lualine on CursorMovedI event

---

lua/lualine/components/diagnostics/sources.lua

In the status bar, Left is "nvim_workspace_diagnostic", Right is "nvim_diagnostic"

Workspace diagnostic component returns diagnostics in the wrong order

---

lua/lualine/components/filename.lua
tests/spec/component_spec.lua

In the current implementation of the path shortening a hidden path segment like e.g. `.config` appears as `.` in the final output, which might be of little help on guessing the real path.
This PR changes the shortening in a way, that hidden path segments are abbreviated to two characters. In the above example this would make `.config` appear as `.c` in the final output.
Generalization idea: Instead of applying this to just hidden files, it might be also an idea to make the maximum length of a segment configurable, viz. `max_segment_length = 3` and apply it to all files. With this configuration  `.config/nvim/lua/config/lualine.lua` would be abbreviated to `.co/nvi/lua/con/lualine.lua`.

Proposed feature: always include one letter on shortened hidden paths

---

lua/lualine/components/filename.lua
tests/spec/component_spec.lua

This makes it behave like the default statusline by have a space between the filename and the following icons (but not between the icons).
While at it, also added new test case to ensure that representation is correct, when both states (modified and readonly) are active at the same time.
fixes #794

fix component(filename) add separator between filename and icons

---

lua/lualine/components/location.lua
tests/spec/component_spec.lua

In location component, display screen column number, not byte length.
This is relevant for lines containing non-latin symbols.
The same issue https://github.com/nvim-lualine/lualine.nvim/issues/362 was already fixed once, but then it was broken again.

fix: display virtual column number in location component

---

lua/lualine/components/diagnostics/config.lua
lua/lualine/highlight.lua
lua/lualine/utils/utils.lua
tests/spec/utils_spec.lua

> **Note**
> Marking as draft because requires #834 to properly handle the `sp` highlight scope.
> Right now this PR contains both commits to prevent tests from failing.
---
Allows passing a list of scopes to `extract_color_from_hllist()`, where each scope is tried sequentially until a matching color is found in the highlight group (return on first match).
The change is fully backwards compatible; if the `scope` parameter is a string, the function can handle that and only tries that one scope.
My main motivation is to allow a sensible fallback to the <ins>underline</ins> color in `config.(default_)diagnostics_color` in case any of the `DiagnosticError`, `DiagnosticWarn`, `DiagnosticHint` or `DiagnosticInfo` highlight groups do not have a foreground color set.
In many IDEs, it is a [common …

Support extracting a fallback color from a highlight group

---

.github/workflows/ci.yml

nvim 0.8 was released and tests should run on the latest stable version.

Test on nvim-0.8

---

lua/lualine/extensions/fzf.lua

This PR adds a statusline extension for [fzf-lua](https://github.com/ibhagwan/fzf-lua), in particular it addresses the discussion we had in https://github.com/nvim-lualine/lualine.nvim/issues/860.
See [cross-post](https://github.com/ibhagwan/fzf-lua/issues/537) for additional reference.
Below is a screen recording showing what it looks like in action :)
https://user-images.githubusercontent.com/15387611/194726388-8ee88056-6d15-4e78-8e22-a6d3b989590d.mov

Add fzf-lua extension

---

README.md
lua/lualine/components/searchcount.lua

Hello :wave: Now with `cmdheight=0`, the search count `[x/x]` that used to be in the right of the command mode buffer when navigating search results is hidden. I added a simple function to restore it via `lualine`, and thought it might be worthwhile to contribute upstream.
Happy to add a bit of documentation in the appropriate locations if this is a welcomed idea

feat: added searchcount component

---

CONTRIBUTING.md

For proper testing a clone of `nvim-web-devicons` is required in the same way as `plenary.vim`. Add this information to `CONTRIBUTING.md` (and fix a typo).

docs: Mention that nvim-web-devicons is required for proper testing

---

lua/lualine/components/filetype.lua
tests/spec/component_spec.lua

With https://github.com/kyazdani42/nvim-web-devicons/pull/125 a filetype based lookup was implemented upstream which can be used to get an icon when a file doesn't have an extension.
fixes #578

fix component(filetype) proper icon based on filetype

---

README.md
lua/lualine/component.lua
lua/lualine/components/buffers/buffer.lua
lua/lualine/components/tabs/tab.lua

I found this undocumented option and it is really useful if I want
to show if buffer is modified in tabline. However I need `tabnr`
for that.

Passing self as second arg to self.options.fmt

---

README.md

Overseer is a task runner plugin: https://github.com/stevearc/overseer.nvim
I was looking to see if lualine had an overseer extension so was digging around in the extensions dir and found it there, but it wasn't listed in the README, so just a short 1 line commit to update the text

Add overseer extension to README

---

lua/lualine/themes/powerline.lua
lua/lualine/themes/powerline_dark.lua

I think, that terminal mode should be rendered as insert if insert mode is activated. This patch sets insert mode  properties to terminal mode in powerline theme. I can update other themes it this behavior is ok.

Render terminal mode as insert

---

README.md
lua/lualine/components/buffers/init.lua
lua/lualine/components/tabs/init.lua
lua/lualine/highlight.lua

I noticed that the color of the buffers component wasn't changing with the other components in my lualine setup as I changed modes:<br>
I attempted to use a function to change the color based on mode, but encountered this visual issue where only part of the background of the active buffer changed:<br>
I fixed that issue in highlight.lua, and added a `get_mode_suffix` function to simplify retrieving the mode suffix from outside of the highlight module.
I also added a `use_mode_colors` option to the buffers, tabs, and windows components (false by default), which automatically sets the colors of those components. 
How it looks now:<br>

Fix dynamic coloring of tabline/winbar components

---

README.md
lua/lualine/components/selectioncount.lua

Implement `selectioncount` component, which shows:
- number of selected characters if selection is within one line,
- number of selected lines if more than one line selected,
- "lines x characters" if mode is visual block.
This is useful in case of `vim.go.cmdheight = 0` option set.
---
- @kraftwerk28 - basic implementation,
- @dmyTRUEk - enhancement.

feat: add selectioncount component

---

README.md
lua/lualine/extensions/lazy.lua

This PR adds an extension for the plugin manager [lazy.nvim](https://github.com/folke/lazy.nvim).
On the corresponding filetype it looks like:

added extension for lazy.nvim

---

lua/lualine/extensions/quickfix.lua

This PR introduces colours to distinguish between quickfix and location list (see screenshot below): I have been using it locally myself for a time and thought to propose it as a PR, should it be of interest for others too.
At the moment I have configured hardcoded highlight colours, however ideally the users could pass them as arguments: I have not been able to understand how (and if) it is possible; I would imagine something along the lines of
```lua
lualine.setup({
extensions = { 
quickfix.setup{ qf = '#...', ll = '#...'}, 
...
}
}
```
perhaps you can direct me to how to achieve it (and I could improve the PR).
https://user-images.githubusercontent.com/15387611/211216863-5ba09dac-45e7-48e8-8b8b-8f03139f05b4.mov

added colours to qf extension to distinguish quickfix and location list

---

lua/lualine/components/searchcount.lua

`searchcount.lua` now checks if the resulting table from `vim.fn.searchcount` is empty to avoid the error.

Fix: `searchcount` error (#1004)

---

README.md
lua/lualine/components/tabs/init.lua
lua/lualine/components/tabs/tab.lua

Allow to switch between different `path` modes:
* `0`: just shows the filename
* `1`: shows the relative path and shorten `$HOME` to `~`
* `2`: shows the full path
* `3`: shows the full path and shorten `$HOME` to `~`
Add an option to set the tab max size (`0` to disable), and uses the same logic as the Buffers module to dynamically shorten the path when the max size is reached.
Add a "modified status", mimicking the default vim/nvim tab bar by showing a symbol when a buffer contained by the tab is modified.

Add options to the Tabs module to align it with the Buffers module

---

lua/lualine/components/branch/git_branch.lua

In repositories that use a git dir which is not accessible by parent path traversal, it is nice to be able to read `GIT_DIR` and use it to show the current branch.
A project where this is important is https://yadm.io/, which is a dotfiles manager that stores its git dir in `~/.local/share/yadm/repo.git`.
I've tested this change locally and it works as expected:

Fall back to GIT_DIR if git dir is not found

---

.github/workflows/ci.yml
README.md
lua/lualine.lua
lua/lualine/components/diagnostics/config.lua
lua/lualine/components/diagnostics/sources.lua
lua/lualine/config.lua
tests/statusline.lua

Users of these versions can still use compatibility tags compat-nvim-0.5 and compat-nvim-0.6 respectively.
BREAKING CHANGE

drop support for nvim-0.5, 0.6 (BREAKING)

---

README.md
lua/lualine/extensions/ctrlspace.lua

PR resulting from discussion in #1117 
statusline when ctrlspace is activated looks like this:

Add ctrlspace extension

---

lua/lualine/components/searchcount.lua

fixes #1087
We could alert the user to the failure, however vim does that well enough.
Tested OK:

fix(#1087): handle searchcount failures

---

lua/lualine/themes/iceberg_dark.lua

make the iceberg dark theme a little more vibrant

---

lua/lualine/components/filename.lua

When you try to open a file with a long filename that has a `%` at the start of one of the path segments, the percent sign will first get escaped and then the path segment that contains it may get shortened to a single character which "unescapes" the percent sign:
1. Original filename: `aaaaaa/bbbbbb/%cccccc/dddddd/file.txt`
2. Escaped filename: `aaaaaa/bbbbbb/%%cccccc/dddddd/file.txt`
3. Shortened filename: `a/b/%/d/file.txt` instead of `a/b/%%/d/file.txt`
This bug is likely more common than it may first seem. I found it by jumping to a function definition which was in a java library class with a URL-like filename (it started with `jdt://`). There were a few `\` symbols encoded as `%5C` that caused lualine to crash.

fix: escape filename after it has been shortened

---

lua/lualine/components/filename.lua
tests/spec/component_spec.lua

Also ran into this issue with the `jdt://` URLs, as reported in #820. Instead of using JDT-specific workarounds like #1030 and #821, let's fix the root cause.
Given a directory structure like `%dir1/%dir2/%actual_%file'`, the shortening process should eliminate the `%` escaping. It currently shortens it to `%/%/%%actual_%%file'` instead of the correct '%%/%%/%%actual_%%file'. The unescaped `%/` is an illegal char sequence.
To address this, it would make sense to run the escaping after shortening has been completed.

fix(#820): Illegal character in filename

---

lua/lualine/extensions/fzf.lua

On non-floating windows the selected element is not supported and showed 'nil'.
This fixes that and also uses fzf's path parser for a cleaner parsing of the
selection.
Closes #1197

fix: fzf extension selected element parsing

---

lua/lualine/components/branch/git_branch.lua

terminal buffers have a different path that did not work to retrieve the branch name. By extracting the path out of the terminal path, the branch name can still resolve even when in term buffers.

fix(branch): extract correct branch name for term buffers

---

lua/lualine/extensions/mason.lua

Fixed mason extension to only load mason-registry when the lualine section is
displayed (on 'mason' filetype). This prevents loading mason when lualine is
loaded.

fix: mason extension lazy loading

---

THEMES.md
lua/lualine/themes/base16.lua

Currently lualine.nvim only supports [nvim-base16](https://github.com/RRethy/nvim-base16), this adds support for [base16-vim](https://github.com/tinted-theming/base16-vim).
[base16-vim](https://github.com/tinted-theming/base16-vim) and [nvim-base16](https://github.com/RRethy/nvim-base16) both use the `base16-` prefix for colorscheme names:
- https://github.com/tinted-theming/base16-vim/tree/main/colors
- https://github.com/RRethy/nvim-base16/tree/master/colors
This causes colorschemes from both plugins to trigger the `lua/lualine/themes/base16.lua`  file, which is why I made the changes in that file.
- Check if a [base16-vim](https://github.com/tinted-theming/base16-vim) colorscheme is active (by testing to see if the first and last colour variables are set). If it is, use the existing …

Add support for base16-vim alongside nvim-base16

---

lua/lualine/components/location.lua

The location component had been previously changed to use
`vim.api.virtcol` (the screen position of the cursor) instead of
`vim.api.col` (the byte position of the cursor), in order to prevent
showing the wrong column when multibyte characters are present.
Unfortunately, the new inlay hints in neovim 0.10 make heavy use of
virtual text, and therefore the column shown in the location component
is often incorrect.
This change fixes it to use `vim.api.charcol`, which correctly handles
variable-width characters without including virtual text.

fix: Location component was showing wrong column with inlay hints.

---

lua/lualine/components/branch/git_branch.lua
lua/lualine/components/filename.lua

Hey, so when using oil file manager the branch is empty when viewing an oil buffer, this is because oil has its own path, now this is a small change to make it work, but I don't really like modifying globally the component like this, maybe this project should have some hooks or apis that the user could override, like `get_buffer_dir` ?
The same problem is with `filename` component and the fix is the same to use the oil api get_current_dir, so thats why I think having a global user editable api for directories would be a great option
https://github.com/nvim-lualine/lualine.nvim/issues/1077
https://github.com/nvim-lualine/lualine.nvim/issues/1077#issuecomment-2119754614

`branch` supports `oil` now

---

lua/lualine/components/diagnostics/sources.lua

In NeoVim 0.10.0 vim.diagnostic.count() was added and can be used instead of vim.diagnostic.get(). I edited vim.diagnostic.get() to be a fallback, if vim.diagnostic.count() is not available. By using vim.diagnostic.count() we avoid using a loop, which should be a minimal performance improvement.

Use vim.diagnostic.count instead of get (Feat #1239)

---

README.md
lua/lualine/components/encoding.lua
tests/spec/component_spec.lua

Inspired by vim-airline, it adds `[BOM]` to the encoding if the file uses byte-order mark

feat: Add BOM indicator to encoding component

---

lua/lualine/components/branch/git_branch.lua

Fix #1274
The PR avoids loading the plugin to check its availability by simply verifying if `oil` is in the package.loaded table. Since its already loaded it uses `require` directly instead of a protected call.

fix: Use package.loaded instead of require to check if oil exists

---

lua/lualine/utils/loader.lua

Fixes https://github.com/nvim-neorocks/rocks.nvim/issues/536.
When lualine.nvim is installed as a luarocks package[^1], the loader can't find the themes on the runtimepath, because
Neovim doesn't keep the runtimepath and `package.path` in sync.
This PR introduces a fallback search of the `package.path` if a theme can't be found on the runtimepath.
[^1]: luarocks installs packages with a non-flat hierarchy, with `lua` and `lib` directories in a separate tree.

fix(loader): look for themes on `package.path`

---

examples/evil_lualine.lua

When using the example of [evil_line.lua](https://github.com/nvim-lualine/lualine.nvim/blob/master/examples/evil_lualine.lua#L163), show the following error:
In neovim 0.12 vim.lsp.get_active_clients() function will be [deprecated](https://neovim.io/doc/user/deprecated.html#vim.lsp.get_active_clients()), vim.lsp.get_clients() solve the problem and works perfectly

Deprecated function in example evil_lualine.lua

---

lua/lualine.lua

When using global status line and "ignore_focus" option together in some cases status line disappear. Can be replicated with "globalstatus = true" and "ignore_focus = { "lazy", "notify" }" and focusing floating window of Lazy or Notify.
Problem is global status line needs refresh scope "window".  Refresh timers set variable named "kind", but refresh function expects variable "scope", becase it's not set it fallback to scope "tabpage".
Fixed by renaming "kind" to "scope" in refresh timers.

Fix automatic refresh variable name

---

lua/lualine/extensions/trouble.lua

Changes in v3 of [Trouble.nvim](https://github.com/folke/trouble.nvim):
- Filetype changed, `Trouble`  to `trouble`.
- The current window's mode information is stored in the variable: `vim.w[win_id].trouble`.
preview:

fix: trouble extension. Works on Trouble.nvim v3 and keep backward compatibility.

---

README.md
lua/lualine/components/lsp_status.lua
tests/spec/component_spec.lua

Closes https://github.com/nvim-lualine/lualine.nvim/issues/1375.
Following an example of a simple LSP progress using notifications: https://github.com/folke/snacks.nvim/blob/main/docs/notifier.md#-examples, we implement a simple `lsp_status` component that:
- Defines an `autocmd` on `LspProgress` to update the spinner state and refreshes Lualine if the state changed
- Displays the list of active LSPs with the corresponding spinner state if supported by the LSP
Not all LSPs support progress (e.g., `bashls` does not). In that case, we simply skip the spinner and display only the LSP name.
LSPs are separated by a configurable delimiter. The progress state symbols are also configurable.
Screenshots:
NOTE: I updated the GitHub actions to use Ubuntu 22.04. The 20.04 image is deprecated (see …

feat: add `lsp_status` component to display active LSPs and progress

---

lua/lualine/components/lsp_status.lua
tests/spec/component_spec.lua

There's no need to do custom approximations when vim.uv.hrtime is not available, because vim.loop.hrtime should work on older nvim versions (see https://github.com/neovim/neovim/pull/22846).
This simplifies the spinner logic and tests.

feat(lsp_status): use vim.loop.hrtime on older nvim versions

---

README.md
lua/lualine.lua

Use case: I'd like to ignore all windows whose buffer's `buftype` is not empty.

feat: allow `ignore_focus` to be set to a `win -> bool` function

---

lua/lualine.lua
lua/lualine/highlight.lua

Use colors from Normal highlight-group to set following highlight groups
- StatusLine
- StatusLineNC
- Tabline
- TabLineFill
- TabLineSel
- Winbar
- WinbarNC
Note: Having default set to Normal group gives us transparency  effect when bg is not chosen

Fixup: fix attr inheritance breaking highlights

---

lua/lualine/components/lsp_status.lua

Fixed lsp_status shows duplicated lsp by additional result table insertion check.

Fix `lsp_status` shows duplicated lsp

---

README.md
lua/lualine/extensions/avante.lua

Extension to add information for [avante](https://github.com/yetone/avante.nvim) windows.
Particularly useful when not using a global status line as it simplifies the display of the avante sidebar

feat: add extension for avante

---

lua/lualine/extensions/avante.lua

In addition to input, output, and "selected files" windows Avante may be using a window for "todos" and a window to show a snippet of code selected by the user. Recognize them.

fix(avante): recognize "todo" and "code" sections
