nvim-lualine/lualine.nvim

README.md, lua/lualine/themes/onedark.lua
Please let me know if there is anything else that needs to be done here. Used [onedark's airline theme in it's repo](https://github.com/joshdick/onedark.vim/blob/master/autoload/airline/themes/onedark.vim) as reference.
=> Porting onedark theme

lua/lualine.lua, lua/lualine/highlight.lua, lua/lualine/utils.lua
Per your request on [Reddit](https://www.reddit.com/r/neovim/comments/kn5wo4/lualinenvim_a_blazing_fast_and_easy_to_configure/ghj5ajp?utm_source=share&utm_medium=web2x&context=3) :)
I also went through and switched other similar cases to use `table.concat`. There were 3, listed below. I am not 100% confident that I translated `drawSection()` correctly.
* `StatusLine()` in `lualine.lua`
* `highlight()` in `lualine/highlight.lua`
* `drawSection()` in `lualine/utils.lua`
=> Use table.concat instead of string concatentation

lua/lualine.lua, lua/lualine/utils.lua
* fixed live colorscheme change also applying to lualine
* fixed theme definition in config not working
=> fixed highlight bug

README.md, THEMES.md, lua/lualine/themes/nord.lua
=> Added nord theme

THEMES.md, lua/lualine/themes/powerline.lua
continuing #22
I think mirroring theme on left(A,B,C) and right(X,Y,Z) is limiting.
I kind of like the left and right structure in lightline.
can we have something like that in lualine ?
Also I feel like the colours in normal mode should be default . if a cirtain modes values aren't defined lualine should fallback to normal modes colors.
=> Added powerline theme

THEMES.md, lua/lualine/themes/forest_night.lua
This is a port of [forest-night](https://github.com/sainnhe/forest-night)'s lightline theme. Let me know if anything needs to be changed!
=> Added forest_night theme

lua/lualine/components/branch.lua
#37 
git branch wasn't changing because git command was being executed in current directory rather then file directory .
I donn't know what the async code actually doing . So there might be a better way to solve it.
=> Fix branch not changing

lua/lualine/highlight.lua
I intruduced it with #47 
Every mode was being rendered as normal mode.
=> Bug fix Theme not rendered properly

THEMES.md, lua/lualine/themes/molokai.lua
=> Add molokai theme

THEMES.md, lua/lualine/themes/16color.lua
=> Add 16color theme

THEMES.md, lua/lualine/themes/papercolor.lua, lua/lualine/themes/papercolor_dark.lua, lua/lualine/themes/papercolor_light.lua
=> Add papercolor theme

README.md, doc/lualine.txt, lua/lualine/components/filename.lua
My bad I didn't test out the example before. I had written it on the fly while writting docs with python slices lol. Also I've introduced a bug while renamng in filename options.
@hoob3rt merge this as soon as you can.
=> (Bug Fix) Fix_filename_component+docs

lua/lualine.lua
Old idea frezee statusline on BufLeave and reactivate on BufEnter
=> BugFix reintroduction of #32

README.md, doc/lualine.txt, doc/tags, lua/lualine/components/signify.lua, lua/lualine/utils/utils.lua
Now Components can apply currect highlights for themselves . I've added colors to signify component.
=> Add colors to signify

lua/lualine/components/diagnostics.lua
adding icons, highlights, some reformats
Choose the colors , Also test it out .
=> Improving diagnostics

lua/lualine/utils/component.lua
=> BugFix: Fix signify causing bad section highlights

doc/lualine.txt
=> Updating docs to reflect master

README.md, doc/lualine.txt, lua/lualine/components/diagnostics.lua
Enable to set symbols for diagnostics.
=> Customize symbols for the diagnostics component

lua/lualine/components/diff.lua
Sometimes async process outputs partial data. Previously that data was processed imediatly causing wrong results. Now the data is processed after async processes finishes
=> BugFix: Wrong data displayed by diff component

lua/lualine/themes/dracula.lua
Dracula colorscheme was poorly made. I fixed command and inactive modes. Also renamed gray color variables to the right ones. Take a look.
=> Fix Dracula theme, make it similar to others

lua/lualine/components/filetype.lua
=> (BugFix) filetype icon not updating with filechange

THEMES.md, lua/lualine/themes/palenight.lua
Adds a theme based on https://github.com/drewtempelmeyer/palenight.vim
=> Add palenight theme

README.md, doc/lualine.txt, lua/lualine.lua, lua/lualine/highlight.lua
Addressing #113
Now lualine can be confugured through vimscript . Checkout docs for example.
=> Feat: Add configuration in viml and through status function

lua/lualine/utils/component.lua
=> Fix diff highlight affecting other component

.gitignore, lua/lualine/components/mode.lua, lua/lualine/highlight.lua
changes:
- fix logical error in highlight.lua
- refactor mode component
- add tags to gitignore
=> fix bug component highlights not blending with bg

EXTENSIONS.md, README.md, lua/lualine.lua, lua/lualine/extensions/fugitive.lua, lua/lualine/extensions/fzf.lua, lua/lualine/extensions/nerdtree.lua
=> feat: changed extension structure & added extensions

lua/lualine/components/diagnostics.lua
=> BugFix: Fix diagnostics highlight extraction

lua/lualine/components/filename.lua
=> Feat: Adding readonly to filestatus

README.md, doc/lualine.txt, lua/lualine/components/diagnostics.lua
Hi!
I want diagnostics with vim-lsp.
Please review this pull request.
https://github.com/prabirshrestha/vim-lsp
vim-lsp has 1.9k stars, so it is popular.
=> feat: add diagnostic sources option vim_lsp

THEMES.md, lua/lualine/themes/everforest.lua
sainnhe changed the name of his repo and theme: https://github.com/sainnhe/everforest/issues/43
=> forest_night -> everforest

lua/lualine/components/filename.lua
=> Fix displaying relative paths.

doc/lualine.txt
=> Typo in docs: comparism -> comparison

lua/lualine/init.lua
Handles weird theme types in config & makes code cleaner imo
=> fix: theme type check fix

README.md, lua/lualine/extensions/chadtree.lua, lua/lualine/extensions/nerdtree.lua, lua/lualine/extensions/nvim-tree.lua, lua/lualine/utils/utils.lua
This should resolve all inactive pr's with existing extensions while also making all tree-based extensions be consistent with each other.
Closes #43, closes #44, closes #145, closes #156
=> feat: addad chad&nnvim tree extensions

lua/lualine/components/hostname.lua
=> BugFix: Fix hostname component not working

README.md, doc/lualine.txt
closes #158
should have all the newest updates from README.md
=> docs: updated lualine.txt

lua/lualine/component.lua, lua/lualine/components/diagnostics.lua, lua/lualine/components/diff.lua, lua/lualine/components/special/eval_func_component.lua, lua/lualine/highlight.lua, lua/lualine/init.lua, lua/lualine/themes/auto.lua, lua/lualine/utils/utils.lua
+ Remove cterm from hl_extractor (we don't have a use case for it)
+ fix lint issues
+ apply lua-format
=> Refactor: Remove cterm from hl_extractor

THEMES.md, lua/lualine/themes/modus_vivendi.lua
adds a theme based on modus_vivendi https://protesilaos.com/modus-themes/
vim version of the theme can be though here: https://github.com/ishan9299/modus-theme-vim
=> Add modus_vivendi theme

lua/lualine/components/diff.lua, lua/lualine/components/filename.lua
=> spelling: instence -> instance

README.md, doc/lualine.txt, lua/lualine/components/filename.lua
Let's let users customize these symbols as well. Color would be nice too, eventually.
=> feat(filename): add support for custom filename symbols (modified, readonly)

README.md, doc/lualine.txt, lua/lualine/defaults.lua, lua/lualine/init.lua
Adding a new option in options table named `disabled_filetypes` .
It's a list of filetypes . If current filetyoe is on the list
statusline will be disabled.
closes #202
=> Feat: Disable lualine on specific filetype

lua/lualine/highlight.lua, lua/lualine/init.lua, lua/lualine/utils/section.lua
This reduces startup time.
- Only load default config when needed
- Only load cterm colors when needed
- Async load components and theme
Without these changes according to packers [profiler](https://github.com/wbthomason/packer.nvim#profiling) lualine takes around 73ms in my device with these changes around 12ms . Thats **6x** improvement.
norcallies [profiler](https://github.com/norcalli/profiler.nvim) shows similar improvements.
=> Performence improvments

lua/lualine/highlight.lua, lua/lualine/init.lua, lua/lualine/utils/section.lua
Reverts hoob3rt/lualine.nvim#205
=> Revert "Performence improvments"

README.md, doc/lualine.txt
=> docs: updated luline.txt

lua/lualine/components/filename.lua
=> refactor: remove filename warning

THEMES.md, lua/lualine/themes/horizon.lua
Based off the Horizon VS-Code  theme.
=> Add Horizon theme

lua/lualine/components/diagnostics/config.lua
I replaced battle.net icon with xf838 as it described in comment.
But I think it is still not appropriate icon and I'd appreciate suggestion about it.
=> fix: Replace battle.net icon with sharing screen

README.md, doc/lualine.txt, lua/lualine/extensions/symbols-outline.lua
Just simply support [symbols-outline](https://github.com/simrat39/symbols-outline.nvim).
Please check it out.
Thank you.
=> Support symbols-outline extension

README.md
=> Fix example buffers configuration

README.md, doc/lualine.txt, lua/lualine/extensions/aerial.lua
Simply support [aerial.nvim](https://github.com/stevearc/aerial.nvim)
Please check it out. 
Many thanks.
=> Extension for aerial.nvim

THEMES.md, lua/lualine/themes/ayu.lua
Hi! I use Ayu and noticed this theme did not use the adaptive `background` setting. This was presumably because Ayu has 2 dark themes. But I have accounted for that here. I tested this and it works and is much better for light/dark switching :)
=> Ayu adaptive background

lua/lualine/components/filetype.lua
=> handle cases where filetype icon highlight is not set

README.md, doc/lualine.txt, lua/lualine.lua, lua/lualine/config.lua, lua/tests/spec/lualine_spec.lua
=> feat: add support for global statusline

README.md, lua/lualine/extensions/neo-tree.lua
I added extension for https://github.com/nvim-neo-tree/neo-tree.nvim
=> Add neo-tree extension

README.md, lua/lualine/components/buffers/buffer.lua, lua/lualine/components/buffers/init.lua, tests/spec/lualine_spec.lua
This is a rough draft to address #668.
Still needs documentation (and maybe a test spec), which I will add if the feature request is approved.
=> Add option to show buffer number + alternate file icon

README.md, lua/lualine/extensions/nvim-dap-ui.lua
Add [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui) extension
=> feat: add nvim-dap-ui extension

README.md, doc/lualine.txt, lua/lualine.lua, lua/lualine/components/location.lua, lua/lualine/components/progress.lua, lua/lualine/config.lua, tests/spec/component_spec.lua, tests/spec/lualine_spec.lua
=> feat: allow lualine to ignore focus on specific filetypes.

lua/lualine/utils/mode.lua
Following https://github.com/neovim/neovim/pull/19584
=> feat: add support for mode ntT

README.md, lua/lualine/components/filename.lua
Add `[New]` symbol for new file.
=> [filename] support detect new file status

lua/lualine/components/filetype.lua
I'm not yet that familiar with the codebase please guide me if there are any inconsistencies :)
=> fix component(filetype) to return default icon instead of nothing

lua/lualine/extensions/overseer.lua
This PR adds a simple [overseer.nvim](https://github.com/stevearc/overseer.nvim) extension.
=> Add overseer extension.

README.md
Please correct me if I'm wrong but I think there should be a coma here
=> Add missing coma to README.md - filename component

README.md
ain't much, but it's honest work. thx for the continued work on this great plugin
=> fix README.md typos

lua/lualine/components/progress.lua
Fix for https://github.com/nvim-lualine/lualine.nvim/issues/849
Behaviour before the fix:
https://user-images.githubusercontent.com/104234283/222956745-00b6a255-79f6-4713-bbec-c8dda2267795.mp4
Behaviour after the fix:
https://user-images.githubusercontent.com/104234283/222956781-9038d066-b9ca-4883-94a7-e7575a8bab80.mp4
=> fix: progress component changes size while scrolling

README.md, lua/lualine/components/datetime.lua
Just a simple datetime component I created for my own config.
=> Add datetime component

README.md, lua/lualine/component.lua, tests/spec/component_spec.lua
=> feat: add draw_empty option to always draw component event when it's empty

examples/evil_lualine.lua, lua/lualine/components/diagnostics/config.lua, tests/spec/lualine_spec.lua
=> fix: replace deprecated nerdfont icons

README.md, lua/lualine/components/diff/init.lua
Added this highlight group extract to allow colorschemes to customize the diff color different from `GitSigns`
=> Added hlgroup for `diff` of lualine

README.md, lua/lualine/extensions/mason.lua
=> Added extension for mason

lua/lualine/extensions/quickfix.lua
Reverts nvim-lualine/lualine.nvim#933
=> Revert "added colours to qf extension to distinguish quickfix and location list"

README.md, lua/lualine/extensions/oil.lua
Show a current directory when opening an [oil.nvim](https://github.com/stevearc/oil.nvim) buffer
=> feat: add oil.nvim extension to show current directory

lua/lualine/highlight.lua
=> feat: Allow cterm highlight number through

examples/evil_lualine.lua
=> Update evil_lualine.lua diagnostics colors.

README.md, lua/lualine.lua, lua/lualine/config.lua, lua/lualine/utils/nvim_opts.lua, tests/spec/lualine_spec.lua
debounce updates for 100ms while setting the options
=> Fixup: fix flickering in lualine

README.md, lua/lualine/extensions/assistant.lua
Implement a extension support for [assistant.nvim](https://github.com/A7Lavinraj/assistant.nvim)
=> [FEAT] Add `assistant` as new extension
